base_url = "https://mabez.dev"

# Used in RSS by default
title = "Scott Mabin"
description = "Scott Mabin's blog"
# The default language, used in RSS
default_language = "en"

# Whether to generate a RSS feed automatically
generate_feed = true
feed_filename = "rss.xml"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "hermit_zola"

taxonomies = [
    {name = "tags", rss = true}
]

[markdown]
render_emoji = true
# Highlight all code blocks found
highlight_code = true
# Which theme to use for the code highlighting.
# See below for list of accepted values
# highlight_theme = "visual-studio-dark"
highlight_theme = "base16-ocean-dark"

[link_checker]
internal_level = "error"
external_level = "warn"

[extra]
home_subtitle = ""

footer_copyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

hermit_menu = [
    { link = "/blog/posts", name = "Blog" },
]

hermit_social = [
    { name = "linkedin", link = "https://www.linkedin.com/in/scott-mabin" },
    { name = "github", link = "https://github.com/mabezdev" },
]

[extra.author]
name = "Scott Mabin"
email = "scott@mabez.dev"

[extra.google_analytics]
enable = true
id = "UA-146726046-1"
